;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-paren
        helm-M-x
        kill-rectangle
        kill-region
        minibuffer-keyboard-quit
        sp--self-insert-command
        sp-backward-delete-char
        ))

(setq mc/cmds-to-run-once
      '(
        calc-quit
        coffee-dedent-line-backspace
        helm-keyboard-quit
        ))
